// Todo el contenido editable vive aquí. Los componentes solo se ocupan de presentarlo.
export const profile = {
  name: 'Juan David Durán Garzón', shortName: 'Juan Durán', email: 'juangarzonmani@gmail.com',
  location: 'Ocaña, Colombia', portrait: '/images/Hero.png',
  social: { github: 'https://github.com/DuranGarzonDev', linkedin: 'https://www.linkedin.com/in/juangdev', instagram: 'https://instagram.com/jddurangarzon', whatsapp: 'https://wa.me/34657230662' },
};

export const projects = [
  { id: 'jamundi', year: '2025', repo: 'https://github.com/DuranGarzonDev/jamundi-conectada', accent: 'sage', tech: ['Python', 'Streamlit', 'Pandas', 'Plotly', 'GeoPandas'] },
  { id: 'sensor-game', year: '2026', repo: 'https://github.com/DuranGarzonDev/SensorGamePy', accent: 'clay', tech: ['Python', 'MediaPipe', 'OpenCV', 'Pymunk'] },
  { id: 'bwelfare', year: '2026', repo: 'https://github.com/DuranGarzonDev/BewelfareB2B', secondaryRepo: 'https://github.com/DuranGarzonDev/BWelfarePersona', accent: 'ink', tech: ['Angular', 'Node.js', 'PostgreSQL', 'MongoDB', 'AWS'] },
  { id: 'advent', year: '2025', repo: 'https://github.com/DuranGarzonDev/AdventoCodeProgram', accent: 'sand', tech: ['Python', 'C++', 'Algoritmos', 'Optimización'] },
  { id: 'pcwable', year: '2022', repo: 'https://github.com/DuranGarzonDev/PcWable', accent: 'sky', tech: ['Desarrollo web', 'Arquitectura', 'Git'] },
];

const es = {
  skip: 'Saltar al contenido',
  back: 'Volver arriba',
  nav: { work: 'Proyectos', path: 'Trayectoria', about: 'Perfil', contact: 'Contacto', menu: 'Menú', home: 'Inicio', changeLanguage: 'Cambiar idioma', changeTheme: 'Cambiar tema' },
  hero: { eyebrow: 'Desarrollador de software e ingeniero de sistemas', title: 'Construyo software útil para problemas que importan.', intro: 'Trabajo entre producto, datos e ingeniería. Convierto necesidades complejas en experiencias claras, sistemas mantenibles y decisiones respaldadas por evidencia.', primary: 'Explorar mi trabajo', secondary: 'Hablemos de un proyecto', availability: 'Disponible para oportunidades y colaboraciones', locationLabel: 'Trabajando desde', portraitAlt: 'Retrato de Juan David Durán Garzón', illustrationAlt: 'Ilustración de un desarrollador trabajando en su portátil' },
  manifesto: { label: 'Cómo trabajo', text: 'Me interesa el software que se entiende, se puede mantener y mejora una situación real. Primero escucho y modelo el problema; después elijo la tecnología.', principles: ['Claridad antes que complejidad', 'Decisiones con contexto', 'Interfaces accesibles', 'Entrega y aprendizaje continuo'] },
  process: { eyebrow: 'Método de trabajo', title: 'Las buenas ideas necesitan un proceso que resista la realidad.', intro: 'No separo diseño, código y validación. Trabajo en ciclos pequeños que permiten aprender sin perder la dirección del producto.', illustrationAlt: 'Ilustración del proceso de desarrollo de software', steps: [{ number: '01', title: 'Planear', text: 'Entender el problema, las personas, los límites y cómo sabremos que funcionó.' }, { number: '02', title: 'Desarrollar', text: 'Construir una solución simple, modular y observable antes de añadir complejidad.' }, { number: '03', title: 'Probar', text: 'Validar comportamiento, accesibilidad, rendimiento y comprensión con evidencia.' }, { number: '04', title: 'Mejorar', text: 'Usar lo aprendido para refinar el producto y conservar las decisiones importantes.' }] },
  projects: {
    eyebrow: 'Trabajo seleccionado', title: 'Proyectos con contexto, no solo capturas.', intro: 'Una selección de sistemas donde combiné investigación, arquitectura, experiencia de usuario e implementación.', details: 'Leer caso', repository: 'Ver repositorio', secondRepository: 'Aplicación complementaria', close: 'Cerrar', labels: { problem: 'El problema', approach: 'El enfoque', outcome: 'El resultado' },
    items: {
      jamundi: { category: 'Datos abiertos · Tecnología cívica', title: 'Jamundí Conectada', summary: 'Un sistema para priorizar inversión en conectividad rural mediante datos territoriales y criterios verificables.', problem: 'La información sobre conectividad estaba fragmentada y no permitía comparar zonas con rapidez.', approach: 'Consolidé fuentes públicas, diseñé un ranking de prioridad y construí un dashboard con mapa, alertas, siete vistas analíticas y exportación de reportes.', outcome: 'El resultado convierte datos técnicos en una herramienta de consulta orientada a decisiones de infraestructura.' },
      'sensor-game': { category: 'Interacción persona–computador', title: 'Plataforma controlada por gestos', summary: 'Juego físico 2D en el que la posición y rotación de una mano controlan una plataforma en tiempo real.', problem: 'Traducir movimiento humano impreciso en un control estable y comprensible dentro de una simulación física.', approach: 'Integré 21 puntos de MediaPipe, cálculo angular, suavizado de señal, OpenCV y colisiones mediante Pymunk.', outcome: 'Una experiencia reproducible que conecta visión por computador, matemáticas e interacción tangible.' },
      bwelfare: { category: 'Producto SaaS · Recursos humanos', title: 'Bwelfare', summary: 'Ecosistema de aplicaciones para organizar procesos de bienestar y gestión de personas dentro de organizaciones.', problem: 'Los equipos necesitan reunir información, seguimiento y operaciones de talento en una experiencia coherente.', approach: 'Separé las experiencias B2B y de persona, trabajando una arquitectura web con persistencia relacional y documental y servicios en la nube.', outcome: 'Una base de producto modular preparada para evolucionar por dominios y perfiles de usuario.' },
      advent: { category: 'Algoritmos · Programación competitiva', title: 'Advent of Code', summary: 'Colección de soluciones a retos de lógica, optimización y modelado algorítmico.', problem: 'Resolver problemas con restricciones cambiantes, entradas extensas y múltiples caminos posibles.', approach: 'Modelé cada reto, comparé estrategias y escribí soluciones verificables en Python y C++.', outcome: 'Práctica sostenida de descomposición, estructuras de datos, análisis de complejidad y depuración.' },
      pcwable: { category: 'Proyecto temprano · Desarrollo web', title: 'PcWable', summary: 'Uno de mis primeros proyectos completos y un registro visible de mi evolución como desarrollador.', problem: 'Pasar de ejercicios aislados a organizar una aplicación con estructura, recursos y control de versiones.', approach: 'Construí el proyecto de extremo a extremo y documenté su evolución en Git.', outcome: 'La base práctica sobre la que desarrollé criterios posteriores de arquitectura y mantenibilidad.' },
    },
  },
  path: {
    eyebrow: 'Trayectoria', title: 'Experiencia que conecta soporte, producto e investigación.', workLabel: 'Experiencia', educationLabel: 'Formación',
    work: [{ period: '2022 — 2024', role: 'Junior Software Developer', place: 'Institución Educativa Rural Los Mesones', location: 'Colombia · Remoto', bullets: ['Automaticé diagnóstico y resolución de incidentes con scripts en Python.', 'Organicé una base de conocimiento para acelerar soporte y conservar decisiones.', 'Traduje necesidades de usuarios en soluciones junto a un equipo multidisciplinar.'] }],
    education: [
      { period: '2025 — 2026', role: 'Movilidad en Ingeniería Informática', place: 'Universidad de La Laguna', location: 'Tenerife · España', note: 'Computación de alto rendimiento, interacción persona–computador y colaboración internacional.' },
      { period: '2022 — Actualidad', role: 'Ingeniería de Sistemas', place: 'Universidad Francisco de Paula Santander', location: 'Ocaña · Colombia', note: 'Arquitectura de software, datos y liderazgo de proyectos académicos.' },
      { period: '2019 — 2021', role: 'Técnico en Sistemas', place: 'Instituto Técnico Industrial Lucio Pabón Núñez', location: 'Ocaña · Colombia', note: 'Infraestructura TI, mantenimiento, soporte y fundamentos de programación.' },
    ],
  },
  about: { eyebrow: 'Perfil', title: 'Técnico en el detalle, atento al sistema completo.', paragraphs: ['Soy Juan, desarrollador de Ocaña. Mi formación mezcla ingeniería de software, soporte de sistemas, redes, análisis de datos e interacción. Esa amplitud me permite conversar con usuarios, entender restricciones y convertirlas en una implementación concreta.', 'Me siento cómodo aprendiendo tecnologías nuevas, pero no persigo herramientas por novedad. Prefiero sistemas sobrios, documentados y fáciles de continuar por otro equipo.'], focusTitle: 'Áreas de trabajo', focuses: ['Aplicaciones web y SaaS', 'Arquitectura y APIs', 'Datos y visualización', 'Visión por computador', 'Cloud e infraestructura', 'Accesibilidad web'], stackTitle: 'Herramientas habituales', stack: ['JavaScript / TypeScript', 'React / Angular', 'Python', 'Node.js', 'PostgreSQL / MongoDB', 'AWS / Docker', 'Git / Linux', 'Figma'] },
  contact: { eyebrow: 'Contacto', title: '¿Hay un problema interesante que podamos resolver?', text: 'Cuéntame el contexto, qué has probado y qué resultado buscas. Respondo con preguntas concretas y una primera lectura técnica.', email: 'Escribirme por correo', copy: 'Copiar correo', copied: 'Correo copiado', location: 'Zona horaria: Colombia (UTC−5)' },
  footer: 'Diseñado y desarrollado por Juan David Durán Garzón.',
};

export const content = {
  es,
  en: {
    ...es,
    skip: 'Skip to content',
    back: 'Back to top',
    nav: { work: 'Projects', path: 'Journey', about: 'Profile', contact: 'Contact', menu: 'Menu', home: 'Home', changeLanguage: 'Change language', changeTheme: 'Change theme' },
    hero: { eyebrow: 'Software developer and systems engineer', title: 'I build useful software for problems that matter.', intro: 'I work across product, data and engineering, turning complex needs into clear experiences, maintainable systems and evidence-backed decisions.', primary: 'Explore my work', secondary: 'Discuss a project', availability: 'Available for opportunities and collaborations', locationLabel: 'Working from', portraitAlt: 'Portrait of Juan David Durán Garzón', illustrationAlt: 'Illustration of a developer working on a laptop' },
    manifesto: { label: 'How I work', text: 'I care about software that can be understood, maintained and used to improve a real situation. I listen and model the problem first; technology comes afterwards.', principles: ['Clarity before complexity', 'Decisions with context', 'Accessible interfaces', 'Continuous delivery and learning'] },
    process: { eyebrow: 'Working method', title: 'Good ideas need a process that survives reality.', intro: 'I do not separate design, code and validation. I work in small cycles that make room for learning without losing product direction.', illustrationAlt: 'Illustration of the software development process', steps: [{ number: '01', title: 'Plan', text: 'Understand the problem, the people, the constraints and how success will be measured.' }, { number: '02', title: 'Build', text: 'Create a simple, modular and observable solution before adding complexity.' }, { number: '03', title: 'Test', text: 'Validate behavior, accessibility, performance and comprehension with evidence.' }, { number: '04', title: 'Improve', text: 'Use what was learned to refine the product and preserve important decisions.' }] },
    projects: {
      ...es.projects, eyebrow: 'Selected work', title: 'Projects with context, not just screenshots.', intro: 'A selection of systems where I combined research, architecture, user experience and implementation.', details: 'Read case', repository: 'View repository', secondRepository: 'Companion application', close: 'Close', labels: { problem: 'The problem', approach: 'The approach', outcome: 'The outcome' },
      items: {
        jamundi: { category: 'Open data · Civic technology', title: 'Jamundí Conectada', summary: 'A system that helps prioritize rural connectivity investment using territorial data and verifiable criteria.', problem: 'Connectivity information was fragmented and made it difficult to compare areas quickly.', approach: 'I consolidated public sources, designed a priority ranking and built a dashboard with a map, alerts, seven analytical views and report exports.', outcome: 'The result turns technical data into an infrastructure decision-support tool.' },
        'sensor-game': { category: 'Human–computer interaction', title: 'Gesture-controlled platform', summary: 'A 2D physics game where hand position and rotation control a platform in real time.', problem: 'Translating imprecise human movement into stable, understandable control within a physics simulation.', approach: 'I integrated 21 MediaPipe landmarks, angle calculation, signal smoothing, OpenCV and Pymunk collisions.', outcome: 'A reproducible experience connecting computer vision, mathematics and tangible interaction.' },
        bwelfare: { category: 'SaaS product · Human resources', title: 'Bwelfare', summary: 'An application ecosystem for organizing employee wellbeing and people-management processes.', problem: 'Teams need to bring talent information, tracking and operations together in a coherent experience.', approach: 'I separated B2B and employee experiences using a web architecture with relational and document persistence plus cloud services.', outcome: 'A modular product foundation that can evolve by domain and user profile.' },
        advent: { category: 'Algorithms · Competitive programming', title: 'Advent of Code', summary: 'A collection of solutions for logic, optimization and algorithmic modeling challenges.', problem: 'Solving problems with changing constraints, large inputs and multiple possible approaches.', approach: 'I modeled each challenge, compared strategies and wrote verifiable Python and C++ solutions.', outcome: 'Sustained practice in decomposition, data structures, complexity analysis and debugging.' },
        pcwable: { category: 'Early project · Web development', title: 'PcWable', summary: 'One of my first complete projects and a visible record of my development as an engineer.', problem: 'Moving from isolated exercises to organizing an application with structure, assets and version control.', approach: 'I built the project end to end and documented its evolution in Git.', outcome: 'The practical foundation for my later architecture and maintainability criteria.' },
      },
    },
    path: {
      eyebrow: 'Journey', title: 'Experience connecting support, product and research.', workLabel: 'Experience', educationLabel: 'Education',
      work: [{ period: '2022 — 2024', role: 'Junior Software Developer', place: 'Los Mesones Rural Educational Institution', location: 'Colombia · Remote', bullets: ['Automated incident diagnosis and resolution with Python scripts.', 'Organized a knowledge base to accelerate support and preserve decisions.', 'Translated user needs into solutions with a multidisciplinary team.'] }],
      education: [
        { period: '2025 — 2026', role: 'Computer Engineering Mobility Program', place: 'University of La Laguna', location: 'Tenerife · Spain', note: 'High-performance computing, human–computer interaction and international collaboration.' },
        { period: '2022 — Present', role: 'Systems Engineering', place: 'Francisco de Paula Santander University', location: 'Ocaña · Colombia', note: 'Software architecture, data and academic project leadership.' },
        { period: '2019 — 2021', role: 'Systems Technician', place: 'Lucio Pabón Núñez Technical Institute', location: 'Ocaña · Colombia', note: 'IT infrastructure, maintenance, support and programming fundamentals.' },
      ],
    },
    about: { eyebrow: 'Profile', title: 'Technical in the details, attentive to the whole system.', paragraphs: ['I am Juan, a developer from Ocaña. My background combines software engineering, systems support, networks, data analysis and interaction. That breadth helps me talk to users, understand constraints and turn them into a concrete implementation.', 'I am comfortable learning new technologies, but I do not chase tools for novelty. I prefer restrained, documented systems that another team can continue.'], focusTitle: 'Areas of work', focuses: ['Web applications and SaaS', 'Architecture and APIs', 'Data and visualization', 'Computer vision', 'Cloud and infrastructure', 'Web accessibility'], stackTitle: 'Regular tools', stack: es.about.stack },
    contact: { eyebrow: 'Contact', title: 'Is there an interesting problem we could solve?', text: 'Tell me the context, what you have tried and what outcome you need. I will reply with concrete questions and an initial technical perspective.', email: 'Send an email', copy: 'Copy email', copied: 'Email copied', location: 'Time zone: Colombia (UTC−5)' },
    footer: 'Designed and developed by Juan David Durán Garzón.',
  },
};
